package com.the.raise.dao;

import com.the.raise.model.RaiseWin;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface RaiseWinMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_win
     *
     * @mbggenerated 插入中奖人信息
     */
    int insertRaiseWin(RaiseWin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_win
     *
     * @mbggenerated 上期获奖名单
     */
    List<RaiseWin> selectRaiseWinList(Integer wperiodsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_win
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RaiseWin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_win
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RaiseWin record);
}