package com.the.raise.dao;

import com.the.raise.model.RaiseSystem;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface RaiseSystemMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_system
     *
     * @mbggenerated 根据系统设置名查询系统设置值
     */
    String selectRaiseSystemBySysname(String sysname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_system
     *
     * @mbggenerated 根据系统设置名更改系统设置值
     */
    int updateRaiseSystemBySysname(RaiseSystem record);

}