package com.the.raise.dao;

import com.the.raise.model.RaiseBet;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
import java.util.Map;

@Mapper
public interface RaiseBetMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_bet
     *
     * @mbggenerated 用户投注
     */
    int insertBet(RaiseBet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_bet
     *
     * @mbggenerated 当前期投注编号
     */
    int queryThisBetNumber(Map thisValue);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_bet
     *
     * @mbggenerated 根据期数和客户号查询投注信息
     */
    List<RaiseBet> queryMyThisRaiseBetList(RaiseBet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_bet
     *
     * @mbggenerated 根据期数查询投注信息
     */
    List<RaiseBet> queryMyThisRaiseBetListByBperiodsid(RaiseBet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_bet
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RaiseBet record);
}