package com.the.raise.dao;

import com.the.raise.model.RaisePeriods;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface RaisePeriodsMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_periods
     *
     * @mbggenerated 新开期数
     */
    int AddRaisePeriods(RaisePeriods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_periods
     *
     * @mbggenerated 查询期数信息
     */
    List<RaisePeriods> selectRaisePeriodsList();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_periods
     *
     * @mbggenerated 用户下注更新总金额，投注总数
     */
    int updateByPrimaryKey(RaisePeriods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_periods
     *
     * @mbggenerated 查询众筹总期数
     */
    int QueryRaisePeriodsNumber();

}