package com.the.raise.service;

import com.the.raise.model.RaiseRecord;

import java.util.List;

/**
 * @Auther: T-luot
 * @Date: 2019/10/21 17:43
 * @Description:
 */
public interface RaiseRecordService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_record
     *
     * @mbggenerated 记录交易流水
     */
    int insertRaiseRecord(RaiseRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_record
     *
     * @mbggenerated 查询我的交易流水
     */
    List<RaiseRecord> selectMyRaiseRecord(RaiseRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_record
     *
     * @mbggenerated 查询我的代理收益
     */
    List<RaiseRecord> selectMyRaiseAgency(RaiseRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_record
     *
     * @mbggenerated 查询充值信息
     */
    List<RaiseRecord> selectTopUpMoneyList(RaiseRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_record
     *
     * @mbggenerated 根据流水号充值信息
     */
    RaiseRecord selectTopUpMoneyByRno(String rno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_record
     *
     * @mbggenerated 更新流水信息
     *
     */
    int updateByPrimaryKey(RaiseRecord record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_record
     *
     * @mbggenerated 查询代理信息
     */
    List<RaiseRecord> selectAgencyMoneyList(RaiseRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_record
     *
     * @mbggenerated 查询待处理提现信息
     */
    List<RaiseRecord> selectMyWithdrawal(RaiseRecord record);

}
