package com.the.raise.service;

import com.the.raise.model.RaiseWin;

import java.util.List;

/**
 * @Auther: T-luot
 * @Date: 2019/10/21 17:43
 * @Description:
 */
public interface RaiseWinService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_win
     *
     * @mbggenerated 上期获奖名单
     */
    List<RaiseWin> selectRaiseWinList(Integer wperiodsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_win
     *
     * @mbggenerated 插入中奖人信息
     */
    int insertRaiseWin(RaiseWin record);
}
