package com.the.raise.service;

import com.the.raise.model.RaiseUser;

import java.util.List;

/**
 * @Auther: T-luot
 * @Date: 2019/10/21 17:43
 * @Description:
 */
public interface RaiseUserService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_user
     *
     * @mbggenerated 用户注册
     */
    int AddRaiseUser(RaiseUser record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_user
     *
     * @mbggenerated [登陆] 根据手机号查询密码
     */
    RaiseUser QueryRaiseUserByPhone(String phone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_user
     *
     * @mbggenerated 根据手机号查询密码
     */
    RaiseUser getRaiseUser(String phone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_user
     *
     * @mbggenerated 根据客户号查询用户
     */
    RaiseUser QueryRaiseUserByUserid(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_user
     *
     * @mbggenerated 用户账户变更
     */
    int UpdateRaiseUserByUserid(RaiseUser record, Float money, Integer gold, Integer prize);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_user
     *
     * @mbggenerated 根据用户类型查询用户总数
     */
    int QueryRaiseUserByIdentity(String identity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_user
     *
     * @mbggenerated 根据身份查询用户
     */
    List<RaiseUser> QueryRaiseUserListByIdentity(String identity);

}
