package com.the.raise.service;

import com.the.raise.model.RaiseAgency;

import java.util.List;

/**
 * @Auther: T-luot
 * @Date: 2019/10/21 17:43
 * @Description:
 */
public interface RaiseAgencyService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_agency
     *
     * @mbggenerated 新增代理信息
     */
    int insertRaiseAgency(RaiseAgency record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_agency
     *
     * @mbggenerated 查询本人代理记录
     */
    RaiseAgency selectRaiseAgency(String acustomer);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_agency
     *
     * @mbggenerated 查询本人代理记录
     */
    List<RaiseAgency> selectRaiseAgencyList();
}
