package com.the.raise.model;

import lombok.Data;

@Data
public class RaiseWin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_win.wcode
     *
     * @mbggenerated 中奖名单编号
     */
    private Integer wcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_win.wperiodsid
     *
     * @mbggenerated 名单所属期号
     */
    private Integer wperiodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_win.wuserid
     *
     * @mbggenerated 名单用户编号
     */
    private String wuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_win.wnoun
     *
     * @mbggenerated 用户中奖名次
     */
    private String wnoun;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_win.wmoney
     *
     * @mbggenerated 用户获奖金额
     */
    private Float wmoney;
}