package com.the.raise.model;

import lombok.Data;

import java.util.Date;
@Data
public class RaiseAgency {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_agency.acustomer
     *
     * @mbggenerated 客户号
     */
    private String acustomer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_agency.aprovince
     *
     * @mbggenerated 代理省
     */
    private String aprovince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_agency.acity
     *
     * @mbggenerated 代理市
     */
    private String acity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_agency.aprice
     *
     * @mbggenerated 代理价格
     */
    private Float aprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_agency.adate
     *
     * @mbggenerated 代理时间
     */
    private Date adate;

}