package com.the.raise.model;

import lombok.Data;

@Data
public class RaisePeriods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_periods.serial
     *
     * @mbggenerated 期数编号
     */
    private int pserial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_periods.amount
     *
     * @mbggenerated 期数总金额
     */
    private Float pamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_periods.state
     *
     * @mbggenerated 期数状态
     */
    private String pstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_periods.sum
     *
     * @mbggenerated 投注总数
     */
    private Integer psum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_periods.details
     *
     * @mbggenerated 开奖详情
     */
    private String pdetails;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_periods.describe
     *
     * @mbggenerated 期数描述
     */
    private String pdescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_periods.subjection
     *
     * @mbggenerated 投注隶属
     */
    private String psubjection;

}