package com.the.raise.model;

import lombok.Data;

import java.util.Date;

@Data
public class RaiseRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_record.rno
     *
     * @mbggenerated 流水号
     */
    private String rno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_record.rclient
     *
     * @mbggenerated 交易客户号
     */
    private String rclient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_record.rtype
     *
     * @mbggenerated 交易类型
     */
    private String rtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_record.rmonny
     *
     * @mbggenerated 交易金额
     */
    private Float rmonny;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_record.rgoldnum
     *
     * @mbggenerated 交易金币数
     */
    private Integer rgoldnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_record.rprizenum
     *
     * @mbggenerated 交易奖卷数
     */
    private Integer rprizenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_record.rstate
     *
     * @mbggenerated 交易状态
     */
    private String rstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_record.rdescribe
     *
     * @mbggenerated 交易说明
     */
    private String rdescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_record.rdescribe
     *
     * @mbggenerated 流水记录时间
     */
    private Date rdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_record.rdescribe
     *
     * @mbggenerated 操作时间
     */
    private Date setdate;


}