package com.the.raise.model;

import lombok.Data;

import java.util.Date;

@Data
public class RaiseBet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_bet.bid
     *
     * @mbggenerated id
     */
    private Integer bid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_bet.bperiodsid
     *
     * @mbggenerated 投注期数编号
     */
    private Integer bperiodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_bet.buserid
     *
     * @mbggenerated 用户客户号
     */
    private String buserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_bet.bprovince
     *
     * @mbggenerated 用户所在省
     */
    private String bprovince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_bet.bcity
     *
     * @mbggenerated 用户所在市
     */
    private String bcity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_bet.prizeNumber
     *
     * @mbggenerated 投注奖卷数量
     */
    private Integer prizenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_bet.goldNumber
     *
     * @mbggenerated 投注金币数量
     */
    private Integer goldnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_bet.state
     *
     * @mbggenerated 投注状态
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_bet.date
     *
     * @mbggenerated 投注时间
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raise_bet.betId
     *
     * @mbggenerated 投注号码
     */
    private Integer betid;

}